name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install Fonts
        run: |
          sudo apt-get update
          sudo apt-get install fonts-noto-cjk fonts-noto-cjk-extra
      - name: Install Tectonic
        run: |
          # Need to setup tectonic with `uses statement`
          curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net | sh
      - name: Compile Latex
        run: |
          ./tectonic main.tex
